# Generated by Django 3.0 on 2021-12-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211220_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('AB', 'Absent'), ('P', 'Present')], default='AB', max_length=2),
        ),
    ]
