# Generated by Django 3.0 on 2021-12-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='exam_name',
            field=models.CharField(choices=[('Q', 'Quarterly Examination'), ('H', 'Half Yearly Examination'), ('A', 'Annual Examination')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
