# Generated by Django 3.0 on 2021-12-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_marks_exam_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='subject_name',
            field=models.CharField(choices=[('FL', 'First Language'), ('SL', 'Second Language'), ('E', 'English'), ('M', 'Mathematics'), ('P', 'Physics'), ('B', 'Biology'), ('S', 'Social')], max_length=2),
        ),
    ]
