# Generated by Django 3.0 on 2021-12-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211220_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('A', 'Admin'), ('T', 'Teacher'), ('S', 'Student')], default='S', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='class_year',
            field=models.CharField(choices=[('NUR', 'Kinder Garten'), ('LKG', 'Lower Kinder Garten'), ('UKG', 'Upper Kinder Garten'), ('I', 'First'), ('II', 'Second'), ('III', 'Third'), ('IV', 'Fourth'), ('V', 'Fifth'), ('VI', 'Sixth'), ('VII', 'Seventh'), ('VIII', 'Eighth'), ('IX', 'Ninth'), ('X', 'Tenth')], max_length=4),
        ),
    ]
